### ISSUE TITLE
Change frigate database location Home Assistant Supervised/frigate-hass-addons

### ISSUE THREAD

**Issue by mannysanch** [blakeblackshear/frigate-hass-addons#114]
I'm running home assistant supervised and the full access addon with protection mode disabled; this is the only way I've found to have my tpu and hw accel be recognized. Now the issue I'm having is that my mediafrigate.db is getting randomly recreated when I'm rebooting, or just restarting the addon. I'm am not sure exactly what is prompting this, as it's been happening while getting the tpu and a camera working properly, but it's not happening everytime.

To aliviate this I would like to change the location of mediafrigate.db from /var/lib/docker/overlay2/{docker-id?}/diff/ to a static folder. I see in /usr/share/hassio/addons/git/ccab4aaf/frigate_fa/config.yaml the following entry:
```
environment:
  CONFIG_FILE: /config/frigate.yml

```
Is there anything I can put in this section, or in the file to use a different folder to store the db?

```
environment:
  CONFIG_FILE: /config/frigate.yml
  DATABASE_FILE: /path/to/folder/mediafrigate.db```   


When I was running a docker I didn't have this issue, but wanted to have frigate and home assistant running on the same machine, so had to go the addon route, thanks.

**Comment by blakeblackshear** [comment]
This is already supported: https://docs.frigate.video/configuration/advanced#database

**Comment by mannysanch** [comment]
I edited the config.yml file like so:
```
name: Frigate (Full Access)
version: 0.12.0
panel_icon: "mdi:cctv"
panel_title: Frigate
slug: frigate-fa
description: NVR with realtime local object detection for IP cameras
url: "https://github.com/blakeblackshear/frigate"
image: ghcr.io/blakeblackshear/frigate
startup: application
boot: auto
init: false
webui: "http://[HOST]:[PORT:5000]/"
watchdog: "http://[HOST]:[PORT:5000]/"
ingress: true
ingress_port: 5000
ingress_entry: /
panel_admin: false
homeassistant_api: true
hassio_api: true
ports:
  8555/tcp: 8555
  8555/udp: 8555
  8554/tcp: null
  5000/tcp: null
  1984/tcp: null
  1935/tcp: null
ports_description:
  8555/tcp: WebRTC over tcp
  8555/udp: WebRTC over udp
  8554/tcp: RTSP Restream
  5000/tcp: Web interface (Not required for Hass.io Ingress)
  1984/tcp: go2rtc API
  1935/tcp: RTMP streams
host_network: false
tmpfs: true
full_access: true
privileged:
  - SYS_ADMIN
environment:
  CONFIG_FILE: /config/frigate.yml
**database:
  path: /config/frigate/mediafrigate.db    <---- My edit**
schema:
  plus_api_key: password?
services:
  - "mqtt:want"
arch:
  - amd64
  - aarch64
  - armv7
map:
  - "media:rw"
  - "config:rw"
```
  The db file is still in the same place:
```
/usr/share/hassio/addons/git/ccab4aaf/frigate_fa$ sudo find / -xdev -name 'mediafrigate.db'
/var/lib/docker/overlay2/ec4ec3693d2b9d8f7fe85086d2e573e7261feb801ce4a72cc0dea47c6c938258/diff/mediafrigate.db
/var/lib/docker/overlay2/97d42987178423fd83a704dcd6a47a8c895fe7dd5930361192dc271b9b4b016f/diff/mediafrigate.db

```

I created the folder in this location: 

```
ls -l /usr/share/hassio/homeassistant/
drwxr-xr-x  2 root root      4096 Apr 30 13:50 frigate
```

I checked the log and I see the mentions of migrating and creating the sql tables, but not in the folder I was expecting.
