### ISSUE TITLE
frigate addon

### ISSUE THREAD

**Issue by bend94** [blakeblackshear/frigate-hass-addons#127]
Hi 
I used Frigate in homeassistant
i added two things , 
1/ one link on lovelace (working well):

```
- title: sec
    icon: mdi:cctv
    cards:
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.devant
            live_provider: ha
            camera_name: devant
          - camera_entity: camera.terrasse
            live_provider: ha
            camera_name: terrasse
          - camera_entity: camera.bureau
            live_provider: ha
            camera_name: bureau
          - camera_entity: camera.cuisine
            live_provider: ha
            camera_name: cuisine
          - camera_entity: camera.salon
            live_provider: ha
            camera_name: salon
          - camera_entity: camera.couloir
            live_provider: ha
            camera_name: couloir
          - camera_entity: camera.interphone
            live_provider: ha

    menu:
      buttons:
        image: false
        frigate: true
      button_size: 80px
      mode: above
    live:
      preload: true
      lazy_unload: true
      auto_unmute: true
      transition_effect: slide
      view:
        update_cycle_camera: true
        update_seconds: 20
        default: live
        camera_select: live
      controls:
        next_previous:
          size: 100px
        # style: chevron
        thumbnails:
          media: clips
          size: 80px
          mode: below
        title:
          mode: popup-top-right
          duration_seconds: 3
      lazy_load: true
    event_gallery:
      min_columns: 8
    event_viewer:
      auto_unmute: true
      controls:
        next_previous:
          style: thumbnails
          size: 90px
        thumbnails:
          size: 90px
          mode: below
        title:
          duration_seconds: 8
          mode: popup-top-right
    dimensions:
      aspect_ratio: "16:7"
      aspect_ratio_mode: static
```

2/ icon link in lovelace pointing to my camera:

```
 - title: Jardin
    panel: true
    icon: mdi:tree
    cards:
     - type: picture-elements
       image: "local/jardin.png"
       elements:
         - type: icon
           entity: camera.cuisine
           icon: mdi:cctv
           camera_view: live
           show_name: false
           style:
             color: black
             top: 80%
             left: 52%
             transform: 'scale(1.1,1.1)'
```

The issue with the 2nd solution, when i am not at home (not on the local network but connected with a reverse proxy)
when i click on the icon , the camera is not show or sometime time a while to see the camera
if i am on my local network, when i click on the icon , i can see very well the camera)

Do you know why ?
