### ISSUE TITLE
Add Option to make Frigate AddOn only visible in Menu when user is administrator

### ISSUE THREAD

**Issue by buhito81** [blakeblackshear/frigate-hass-addons#131]
**Describe what you are trying to accomplish and why in non technical terms**
I want to the Frigate AddOn only visible in Menu when user is administrator.

**Describe the solution you'd like**
https://developers.home-assistant.io/docs/add-ons/configuration#optional-configuration-options 

<html>
<body>

panel_admin | bool | true | Make the menu entry only available to users in the admin group.
-- | -- | -- | --

</body>
</html>

**Comment by mpeterson** [comment]
@buhito81 

I worked around this by installing the [hass_ingress integration](https://github.com/lovelylain/hass_ingress) and then defining in `configuration.yaml` the following config:

```
ingress:
  frigate:
    work_mode: hassio
    title: Frigate
    require_admin: true
    icon: mdi:cctv
    url: ccab4aaf_frigate-proxy
```

note: I use `frigate-proxy`, so the slug to put in `url:` might be different for you
