### ISSUE TITLE
Add-on changes camera's person detection sensor on Frigate tracking not alarm

### ISSUE THREAD

**Issue by ENT108** [blakeblackshear/frigate-hass-addons#194]
I use Frigate with Frigate HAOS Add-on. All runs just fine but, I have such config:

```
review:
  detections:
    labels:
      - person

objects:
  track:
    - person
  filters:
    person:
      min_score: 0.72
      threshold: 0.85
```

...and person detection binary sensors for my cameras that come from Frigate Addon fire when min_score is hit and Frigate starts tracking, while its not an alarm/detection according to the config.

It that a bug or a feature?

Thanks
