### ISSUE TITLE
Tapo ffmpeg changes in 16.0-beta1

### ISSUE THREAD

**Issue by mclever** [blakeblackshear/frigate-hass-addons#225]
Detect not working after upgrade to beta 16

Error
Could not find tag for codec pcm_alaw in stream #1, codec not currently supported in container

```

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-restream-low-latency
  output_args:
    record: preset-record-generic-audio-copy

audio:
  enabled: true

go2rtc:
  streams:
    driveway:
      - tapo://password@ip
      #- ffmpeg:rtsp://username:password@ip/stream1
      - ffmpeg:driveway#audio=aac
#    driveway_detect:
#      - rtsp://username:password@ip/stream2
#      - ffmpeg:driveway#audio=aac



cameras:
  driveway:
    mqtt:
    #  enabled: false
      timestamp: false
      bounding_box: false
      quality: 100
     # height: 500
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/driveway
          roles:
            - record
            - audio
#        - path: rtsp://localhost:8554/driveway_detect
#          roles:
            - detect
    onvif:
      host: ip
      port: 2020
      user: username
      password: password
    detect:
      fps: 5
    objects:
      filters:
        car:
          mask: 0.27,0.468,0.787,0.313,1,0.467,1,1,0.428,1


version: 0.16-0
semantic_search:
  enabled: true
  reindex: false
  model_size: large
detect:
  enabled: true
face_recognition:
  enabled: true
  model_size: large
lpr:
  enabled: true
  debug_save_plates: true
classification:
  bird:
    enabled: true
```
