### ISSUE TITLE
More than one Coral devices

### ISSUE THREAD

**Issue by debsahu** [blakeblackshear/frigate-hass-addons#23]
Following up from https://github.com/blakeblackshear/frigate/pull/1009. I have more than one coral devices (3 in my case) and I use the following settings on hassio addon

```yaml
detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1
  coral3:
    type: edgetpu
    device: pci:2
```

I get an error saying pci:0 and pci:2 TPU not found. My guess is only /dev/apex_0 is passed ([reference](https://github.com/blakeblackshear/frigate-hass-addons/blob/4256ca2731277dd9b84b02b42b91053414f144e4/frigate/config.json#L26))

When "Protection Mode" is off everything works as usual, so my guess is the addon does not have access to all PCIe coral devices under protected mode.

![image](https://user-images.githubusercontent.com/24575521/116444771-14219900-a823-11eb-8549-0fdeef35607b.png)

Again I dont know nothing about hassio add-ons can we add /dev/apex_* to see if that would fix the addon working without enabling protection mode?
