### ISSUE TITLE
Not getting last camera entities added to ha

### ISSUE THREAD

**Issue by niemyjski** [blakeblackshear/frigate-hass-addons#4]
I'm using the 1.2 release and I have 4 unifi cameras installed.

```yaml
camera1:
    objects:
      track:
        - person
        - cat
camera2:
    objects:
      track:
        - person
        - cat
        - mouse
camera3:
    objects:
      track:
        - person
        - cat
        - mouse
        - bicycle
        - motorcycle
        - car
        - truck
        - bus
        - bird
        - dog
camera4:
    objects:
      track:
        - person
        - cat
        - mouse
        - bicycle
        - motorcycle
        - car
        - truck
        - bus
        - bird
        - dog
```

I have last camera entities for the first 3 cameras but nothing for camera 4. Am I hitting a limit here because I see the last topic for camera4 in mqtt.
