### ISSUE TITLE
Dog is detected as a person

### ISSUE THREAD

**Issue by SmartM-ui** [blakeblackshear/frigate-hass-addons#47]
Hi @blakeblackshear ,
why even if I have configured the detection of people only, when my dog passes in front of the camera I still receive the detection notice in person?
He is recognized as a person at 65%, sometimes even when I pass in front of the camera he recognizes me as a person at 65%!

Can I improve something?
```
    detect:
      width: 1920 
      height: 1080
      fps: 5
      enabled: True
      max_disappeared: 25

     record:
       enabled: True
       retain_days: 0
       events:
         pre_capture: 5
         post_capture: 5
         objects:
           - person
         required_zones: []
         retain:
           default: 10
           objects:
             person: 10

     # Optional: Camera level object filters config.
     objects:
       track:
         - person
       filters:
         person:
           min_area: 5000
           max_area: 100000
           min_score: 0.4
           threshold: 0.5
```

(the human detection of the webcam works correctly, in fact the official app does not detect the movement of the dog)

Thanks
