### ISSUE TITLE
After updating to 2.3, video feeds show solid green square

### ISSUE THREAD

**Issue by nuansed** [blakeblackshear/frigate-hass-addons#51]
Home Assistant Add-on: Frigate NVR 
Current version: 2.3

Home Assistant Operating System: 
core-2021.10.6
supervisor-2021.10.0
Home Assistant OS 6.5

Hardware: 
Intel NUC 11
Google Coral USB

No problems before the update. 
I updated to the latest version a few hours ago, and immediately after the update all cams display a solid green square instead of the camera footage. 

I tried commenting out the whole ffmpeg section in the config file, which did not help. 

Thanks for the support! 

**Logs show:** 
[2021-10-25 17:34:49] peewee_migrate                 INFO    : There is nothing to migrate
[2021-10-25 17:34:49] frigate.mqtt                   INFO    : MQTT connected
[2021-10-25 17:34:49] detector.coral                 INFO    : Starting detection process: 225
[2021-10-25 17:34:49] frigate.app                    INFO    : Output process started: 227
[2021-10-25 17:34:49] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2021-10-25 17:34:51] frigate.video                  INFO    : Pool: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2021-10-25 17:34:51] frigate.video                  INFO    : RoofLeft: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2021-10-25 17:34:51] frigate.video                  INFO    : GardenTop: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2021-10-25 17:34:51] frigate.video                  INFO    : GardenFront: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2021-10-25 17:34:51] frigate.video                  INFO    : BackFence: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2021-10-25 17:34:51] frigate.video                  INFO    : RoofRight: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2021-10-25 17:34:49] ws4py                          INFO    : Using epoll
[2021-10-25 17:34:49] frigate.app                    INFO    : Camera processor started for Pool: 234
[2021-10-25 17:34:51] frigate.edgetpu                INFO    : TPU found
[2021-10-25 17:34:51] frigate.video                  INFO    : Pool: ffmpeg process is not running. exiting capture thread...
[2021-10-25 17:34:51] frigate.video                  INFO    : RoofLeft: ffmpeg process is not running. exiting capture thread...
[2021-10-25 17:34:51] frigate.video                  INFO    : GardenTop: ffmpeg process is not running. exiting capture thread...
[2021-10-25 17:34:51] frigate.video                  INFO    : GardenFront: ffmpeg process is not running. exiting capture thread...
[2021-10-25 17:34:51] frigate.video                  INFO    : BackFence: ffmpeg process is not running. exiting capture thread...
[2021-10-25 17:34:51] frigate.video                  INFO    : RoofRight: ffmpeg process is not running. exiting capture thread...
[2021-10-25 17:34:49] frigate.app                    INFO    : Camera processor started for GardenFront: 243
[2021-10-25 17:34:49] frigate.app                    INFO    : Camera processor started for GardenTop: 252
[2021-10-25 17:34:49] frigate.app                    INFO    : Camera processor started for BackFence: 260
[2021-10-25 17:34:49] frigate.app                    INFO    : Camera processor started for RoofLeft: 268
[2021-10-25 17:34:49] frigate.app                    INFO    : Camera processor started for RoofRight: 277
[2021-10-25 17:34:49] frigate.app                    INFO    : Capture process started for Pool: 285
[2021-10-25 17:34:49] frigate.app                    INFO    : Capture process started for GardenFront: 290
[2021-10-25 17:34:49] frigate.app                    INFO    : Capture process started for GardenTop: 293
[2021-10-25 17:34:49] frigate.app                    INFO    : Capture process started for BackFence: 299
[2021-10-25 17:34:49] frigate.app                    INFO    : Capture process started for RoofLeft: 303
[2021-10-25 17:34:49] frigate.app                    INFO    : Capture process started for RoofRight: 308
[2021-10-25 17:34:49] ws4py                          INFO    : Using epoll
[2021-10-25 17:34:54] frigate.record                 WARNING : Discarding a corrupt recording segment: RoofRight-20211025173451.mp4
[2021-10-25 17:34:54] frigate.record                 WARNING : Discarding a corrupt recording segment: BackFence-20211025173451.mp4
[2021-10-25 17:34:54] frigate.record                 WARNING : Discarding a corrupt recording segment: GardenFront-20211025173451.mp4
[2021-10-25 17:34:54] frigate.record                 WARNING : Discarding a corrupt recording segment: GardenTop-20211025173451.mp4
[2021-10-25 17:34:54] frigate.record                 WARNING : Discarding a corrupt recording segment: RoofLeft-20211025173451.mp4
[2021-10-25 17:34:54] frigate.record                 WARNING : Discarding a corrupt recording segment: Pool-20211025173451.mp4
[2021-10-25 17:35:09] watchdog.Pool                  ERROR   : FFMPEG process crashed unexpectedly for Pool.
[2021-10-25 17:35:09] watchdog.Pool                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2021-10-25 17:35:09] watchdog.Pool                  ERROR   : You may have invalid args defined for this camera.
[2021-10-25 17:35:09] ffmpeg.Pool.detect             ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
[2021-10-25 17:35:09] ffmpeg.Pool.detect             ERROR   : [flv @ 0x558e0a5bcc00] Video codec hevc not compatible with flv
[2021-10-25 17:35:09] ffmpeg.Pool.detect             ERROR   : Could not write header for output file #1 (incorrect codec parameters ?): Function not implemented

**Config file:** 
```
mqtt:
  host: core-mosquitto
  user: user
  password: pw

detectors:
  coral:
    type: edgetpu

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128

detect:
  width: 3840
  height: 2160
  fps: 5

objects:
  # list of objects to track from labelmap.txt
  track:
    - person
    - bird
    - umbrella
    - dog
    - cat
    - backpack
  filters:
    umbrella:
      threshold: 0.78
    dog:
      threshold: 0.8
    person:
      threshold: 0.7

record:
  enabled: true
  retain_days: 1
  events:
    max_seconds: 300
    pre_capture: 10
    post_capture: 10
    retain:
      # Required: Default retention days
      default: 14

cameras:

  Pool:
    ffmpeg:
      inputs:
        - path: rtsp://user:pw@10.0.1.61:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
            - record
    detect:
      fps: 6
    best_image_timeout: 15
    zones:
      zone_garden_front:
        coordinates: 2551,2160,3039,1960,2635,1494,1972,1739,1966,2160
    objects:
      filters:
        bird:
          mask:
            - 3806,1111,3160,1471,3071,1240,2865,1052,2505,818,2431,1071,2658,1271,2812,1535,3074,1831,3840,1382
        dog: 
          min_area: 6000
          max_area: 70000
          mask:
            - 3806,1111,3160,1471,3071,1240,2865,1052,2505,818,2431,1071,2658,1271,2812,1535,3074,1831,3840,1382
        person:
          min_area: 6000
          max_area: 70000
          mask:
            - 3806,1111,3160,1471,3071,1240,2865,1052,2505,818,2431,1071,2658,1271,2812,1535,3074,1831,3840,1382
        umbrella: 
          min_area: 6000
          max_area: 70000
          mask:
            - 1237,1655,1086,1092,1655,1415,1785,1618,2003,1692,2034,2160,1557,2160
            - 2812,1535,2351,1502,2468,1295,2295,1052,2418,628,2834,822,3283,1403,3840,1138,3840,1354,2945,1935  
    motion:
      mask:
        - 2643,1111,3129,1840,3840,2160,3840,0,0,0,0,2160,1643,2160,1717,1366,1982,1203,2372,905


  GardenFront:
    ffmpeg:
      inputs:
        - path: rtsp://user:pw@10.0.1.64:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
            - record
    detect:
      fps: 6
    best_image_timeout: 15
    zones:
      zone_garden_front:
        coordinates: 3209,855,3840,862,3840,2160,2490,1923,1476,1490,1737,691,3159,716
    objects:
      filters:
        dog: 
          min_area: 6000
          max_area: 70000
        person:
          min_area: 6000
          max_area: 70000
        umbrella: 
          min_area: 6000
          max_area: 70000
          mask:
            - 1015,295,1391,680,3234,640,3178,351,2606,360,2498,0
            - 975,1551,2988,2055,3037,1772,2582,1711,2431,1452,1662,1320,1129,1372
            - 1538,788,1652,849,1637,1006,1520,1000,1418,889
    motion:
      mask:
        - 3840,0,3840,702,3252,655,3200,446,1434,452,1295,800,1120,818,988,1151,1342,1563,1982,1775,3840,2160,0,2160,0,0

  GardenTop:
    ffmpeg:
      inputs:
        - path: rtsp://user:pw@10.0.1.62:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
            - record
    best_image_timeout: 15
    zones:
      zone_garden_back:
        coordinates: 3351,829,2919,367,2490,171,2610,680,2413,760,2228,1092,3172,1446
      zone_garden_top:
        coordinates: 0,531,1474,335,1794,1265,3840,2160,0,2160
    objects:
      filters:
        bird: 
          mask:
            - 2662,551,2615,874,2357,726,2474,458
        dog: 
          min_area: 6000
          max_area: 70000
        person:
          min_area: 6000
          max_area: 1000000
          mask:
          - 2702,0,3840,0,3840,575
          - 1932,286,2077,794,2178,843,2415,508,2058,194
        umbrella: 
          min_area: 6000
          max_area: 70000
          threshold: 0.8
          mask:
            - 2388,351,2628,332,2705,609,2523,800,2252,532
            - 3240,1422,3366,1471,3840,640,3745,440,3363,397,3172,511

  BackFence:
    ffmpeg:
      inputs:
        - path: rtsp://user:pw@10.0.1.65:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
            - record
    best_image_timeout: 15
    zones:
      zone_garden_back:
        coordinates: 0,2160,0,1652,588,1625,831,1314,594,1083,1203,818,1809,643,1778,1225,2025,1529,2320,1397,2794,1455,2945,1077,3840,1348,3840,2160
    objects:
      filters:
        bird:
          mask:
            - 578,972,797,960,858,1200,535,1197
            - 2705,1434,3686,1760,3640,2018,3317,2160,2277,1729
            - 3545,514,3212,458,3166,25,3523,31
            - 2406,268,2425,498,2197,489,2191,268
        dog: 
          min_area: 8000
          max_area: 120000
        person:
          min_area: 8000
          max_area: 190000
          mask:
            - 3603,2063,3375,1983,3369,2160,3578,2160
            - 2243,1769,2711,1412,3483,1680,3412,1935,2585,1948
            - 3840,548,2769,471,2609,689,3840,1046
        umbrella: 
          min_area: 8000
          max_area: 120000
          mask:
            - 86,1526,43,1231,363,1012,717,1246,760,1526
            - 3840,0,3840,806,3652,852,3135,689,2658,1375,1868,1434,1788,271,2074,0

  RoofLeft:
    ffmpeg:
      inputs:
        - path: rtsp://user:pw@10.0.1.66:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
            - record
    best_image_timeout: 15
    zones:
      zone_roof_left:
        coordinates: 0,1167,492,1280,2224,796,2591,766,3702,972,3840,1169,3840,2160,0,2160
    objects: 
      filters:
        person:
          min_area: 6000
          mask:
            - 2908,1218,2803,1188,2849,945,2945,960
        bird:
          mask:
            - 1923,255,1905,409,1788,391,1797,237

  RoofRight:
    ffmpeg:
      inputs:
        - path: rtsp://user:pw@10.0.1.63:554/Streaming/Channels/101/?transportmode=unicast
          roles:
            - detect
            - record
    best_image_timeout: 15
    zones:
      zone_roof_right:
        coordinates: 0,2160,3840,2160,3840,1094,3308,978,3300,632,2937,552,2864,901,1879,723,0,1280
    objects:
      filters:
        person:
          min_area: 6000
          mask:
            - 1800,1271,1520,1255,1489,1618,1788,1649
            - 2717,1951,2794,1197,2508,1114,2323,1794
```
