### ISSUE TITLE
HassOS Beta

### ISSUE THREAD

**Issue by Coolie1101** [blakeblackshear/frigate-hass-addons#67]
**How do I install the HassOS Beta Version?**

`Add-on Store`

![image](https://user-images.githubusercontent.com/28989417/155010618-c2b60208-2dcf-47dc-847f-bc3341a37502.png)

[There are several versions of the addon available:](https://docs.frigate.video/installation/#home-assistant-operating-system-hassos)**
![image](https://user-images.githubusercontent.com/28989417/155010781-8a1cbe84-4366-4559-a29e-a121173e4cdc.png)

**Comment by blakeblackshear** [comment]
It should be showing up now. I had an error in the config.

**Comment by Coolie1101** [comment]
No Integration sensors available with the Beta Version?

**Comment by blakeblackshear** [comment]
Nothing changed there. Check your HA logs to see if the integration needs to be reconfigured.

**Comment by Coolie1101** [comment]
> Nothing changed there. Check your HA logs to see if the integration needs to be reconfigured.

I removed and re-added the integration but it's still the same.

Also, can't figure out why the following automation executes every 1 minute, seems like Person Motion in stuck, it's now 3:15pm and still shows detected from since 12:54pm.

```
alias: Frigate - Notify Detected Object On Porch
description: Object detection notification from Frigate
trigger:
  - platform: mqtt
    topic: frigate/events
condition:
  - condition: template
    value_template: >-
      {{ as_timestamp(now()) -
      as_timestamp(states.binary_sensor.front_door.last_changed) > 60 }}
  - condition: template
    value_template: >-
      {{
      (as_timestamp(now())-as_timestamp(state_attr('automation.frigate_notify_detected_object_on_porch','last_triggered')
      | default(0)) | int > 60) }}
  - condition: template
    value_template: '{{ not ''steps'' in trigger.payload_json[''after''][''current_zones''] }}'
  - condition: template
    value_template: '{{ not ''south_side'' in trigger.payload_json[''after''][''camera''] }}'
action:
  - service: notify.group
    data:
      message: >-
        A {{trigger.payload_json["after"]["label"]}} was detected on the
        {{trigger.payload_json["after"]["camera"]}} camera.
      data:
        photo:
          - url: >-
              hassos_url/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg
            caption: >-
              'A {{trigger.payload_json["after"]["label"]}} was detected at the
              Front {{trigger.payload_json["after"]["entered_zones"]}}'.
  - delay:
      seconds: 20
  - service: notify.group
    data:
      message: Video of {{trigger.payload_json["after"]["label"]}}" detected.
      data:
        video:
          - url: >-
              hassos_url/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/{{trigger.payload_json["after"]["camera"]}}/clip.mp4
            timeout: 1000
            caption: >-
              'Video of {{trigger.payload_json["after"]["label"]}}" detected at
              the Front {{trigger.payload_json["after"]["entered_zones"]}}'.
mode: single
initial_state: true
```

![image](https://user-images.githubusercontent.com/28989417/155400298-7bc3122d-d633-43d7-8141-de9efbfcbec6.png)

**Comment by Coolie1101** [comment]
> It should be showing up now. I had an error in the config.

FYI, beta 0.11.0 seems to be much more stable, no errors in logs even with hardware acceleration enabled.

**Comment by blakeblackshear** [comment]
Have you taken a look at the debug view? Frigate tracks stationary objects and sends an update message for them every minute. Sounds like something is being tracked.

**Comment by Coolie1101** [comment]
> Have you taken a look at the debug 

Seems to be working as intended, or maybe I'm lookin at it wrong.

![image](https://user-images.githubusercontent.com/28989417/155828413-1041da1b-626e-419d-88bc-209011d294b1.png)

**Here's the automation:-**
```
alias: Frigate - Notify Detected Object On Porch
description: Object detection notification from Frigate
trigger:
  - platform: mqtt
    topic: frigate/events
condition:
  - condition: template
    value_template: >-
### Cancel if the front door was open recently - means we are going out.
      {{ as_timestamp(now()) -
      as_timestamp(states.binary_sensor.front_door.last_changed) > 60 }}
  - condition: template
    value_template: >-
### Cancel if this automation ran within the last min.
      {{
      (as_timestamp(now())-as_timestamp(state_attr('automation.frigate_notify_detected_object_on_porch','last_triggered')
      | default(0)) | int > 60) }}
  - condition: template
### Avoid triggering for the following zones.
    value_template: '{{ not ''steps'' in trigger.payload_json[''after''][''current_zones''] }}'
  - condition: template
    value_template: '{{ not ''south_side'' in trigger.payload_json[''after''][''camera''] }}'
action:
  - service: notify.group
    data:
      message: >-
        A {{trigger.payload_json["after"]["label"]}} was detected on the
        {{trigger.payload_json["after"]["camera"]}} camera.
      data:
        photo:
          - url: >-
              http://hass_url/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg
            caption: >-
              'A {{trigger.payload_json["after"]["label"]}} was detected at the
              Front {{trigger.payload_json["after"]["entered_zones"]}}'.
  - delay:
      seconds: 20
  - service: notify.group
    data:
      message: Video of {{trigger.payload_json["after"]["label"]}}" detected.
      data:
        video:
          - url: >-
              http://hass_url/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/{{trigger.payload_json["after"]["camera"]}}/clip.mp4
            timeout: 1000
            caption: >-
              'Video of {{trigger.payload_json["after"]["label"]}}" detected at
              the Front {{trigger.payload_json["after"]["entered_zones"]}}'.
mode: single
initial_state: true
```

**Comment by Coolie1101** [comment]
**Motion Masks**

![image](https://user-images.githubusercontent.com/28989417/155828744-c5e54ddf-10c5-4e85-b171-025dbcd0d580.png)

![image](https://user-images.githubusercontent.com/28989417/155828762-dd754926-8821-486d-8d7d-7e9c6ab4a9bc.png)

![image](https://user-images.githubusercontent.com/28989417/155828781-6f0371c2-8dfc-4fb0-84a6-cd73fba65607.png)

![image](https://user-images.githubusercontent.com/28989417/155828791-29d476b8-f8d9-4379-ad56-5e0046b5b859.png)

**Comment by Coolie1101** [comment]
**Zones**

> Front Door
![image](https://user-images.githubusercontent.com/28989417/155828810-3b33979b-9b74-40d8-8fc7-a5b73ff16cd5.png)

> Porch
![image](https://user-images.githubusercontent.com/28989417/155828824-a9a2dff0-9c87-47eb-bf25-0413867a8d93.png)

>Steps
![image](https://user-images.githubusercontent.com/28989417/155828835-8c721c66-fe63-409c-802d-13eee9392307.png)

**Comment by Coolie1101** [comment]
**Person Object Mask**

![image](https://user-images.githubusercontent.com/28989417/155828868-0ac13d12-7e6e-4551-a18f-379831ec3195.png)

**Comment by Coolie1101** [comment]
**Here are the latest events:-**
![image](https://user-images.githubusercontent.com/28989417/155852562-76a83627-f692-48fb-bd91-efe5ff369949.png)

What I notice, is when the automation is triggered by an object, it executes as expected, but then continues to fire every minute sending an image with no specified object until I restart Frigate.

**Comment by blakeblackshear** [comment]
> then continues to fire every minute sending an image with no specified object until I restart Frigate

This is expected behavior when tracking stationary objects. If you look at the debug view when this is happening, you should see a bounding box for the stationary object.

**Comment by blakeblackshear** [comment]
Click on the camera to view the live stream and then select debug in the top right. Below the stream you have some options to turn on bounding boxes, etc.

**Comment by Coolie1101** [comment]
> Click on the camera to view the live stream and then select debug in the top right. Below the stream you have some options to turn on bounding boxes, etc.

Got it, I could be wrong, but could it be the time in the zone below is what may have been triggering the event, I adjusted the zone, but won't know the effects for sure until tomorrow AM.

**Old Zone**
![image](https://user-images.githubusercontent.com/28989417/155868851-cccb7c8f-0110-4f52-9a75-ae9ef1b10c94.png)

**New Zone**
![image](https://user-images.githubusercontent.com/28989417/155868908-37379219-1756-4aa4-80e0-92a084ddfabd.png)


Any idea how I can troubleshoot the issue with the missing sensors?, I removed and re-added the integration a couple times with the same result.

**Sensors Currently Available**
![image](https://user-images.githubusercontent.com/28989417/155868950-256f1639-f7e8-47e5-88fb-b0948f305d84.png)

**Comment by Coolie1101** [comment]
Any chance of detecting packages/box only if in configured zone's for X amount of time?

**Comment by Coolie1101** [comment]
New error on live stream.

`Error from stream worker: Error opening stream (ERRORTYPE_2, No such file or directory) ccab4aaf-frigate-fa-beta`

**Comment by blakeblackshear** [comment]
> Any chance of detecting packages/box only if in configured zone's for X amount of time?

The model doesn't support packages, but custom models in Frigate+ will.

Some sensors are sent via MQTT, so make sure that is still working properly between HA and Frigate.

> could it be the time in the zone below is what may have been triggering the event

You should definitely add a motion mask over the timestamp if you haven't already, but motion and zones have nothing to do with each other. Zones are only applicable to objects.

**Comment by Coolie1101** [comment]
> but custom models in Frigate+ will
👍 

> Some sensors are sent via MQTT

MQTT seems to be working.
```
{
  "frontdoor": {
    "camera_fps": 5,
    "process_fps": 5,
    "skipped_fps": 0,
    "detection_fps": 0,
    "pid": 221,
    "capture_pid": 226
  },
  "south_side": {
    "camera_fps": 5.1,
    "process_fps": 5.1,
    "skipped_fps": 0,
    "detection_fps": 0,
    "pid": 225,
    "capture_pid": 229
  },
  "detectors": {
    "coral": {
      "inference_speed": 55.4,
      "detection_start": 0,
      "pid": 217
    }
  },
  "detection_fps": 0,
  "service": {
    "uptime": 311,
    "version": "0.11.0-cbf26e0",
    "storage": {
      "/media/frigate/recordings": {
        "total": 235535.3,
        "used": 63994.4,
        "free": 161940.5,
        "mount_type": "ext4"
      },
      "/media/frigate/clips": {
        "total": 235535.3,
        "used": 63994.4,
        "free": 161940.5,
        "mount_type": "ext4"
      },
      "/tmp/cache": {
        "total": 4095,
        "used": 56.4,
        "free": 4038.5,
        "mount_type": "tmpfs"
      },
      "/dev/shm": {
        "total": 4095,
        "used": 1.3,
        "free": 4093.7,
        "mount_type": "tmpfs"
      }
    },
    "temperatures": {}
  }
}
```



> You should definitely add a motion mask

Motion mask already exist.
![image](https://user-images.githubusercontent.com/28989417/155905062-0906776c-99d6-4646-9bf2-ec40ab82efe9.png)

**Comment by Coolie1101** [comment]
Any idea why the automation below is still being executed?

**Debug**
![image](https://user-images.githubusercontent.com/28989417/156600804-610fe5da-414c-4e61-83c3-05b152a5adb6.png)


**Motion Masks**
![image](https://user-images.githubusercontent.com/28989417/156600999-800c6cdc-2845-4fd9-bed4-866d8a92ddd2.png)


**Zones**
![image](https://user-images.githubusercontent.com/28989417/156601125-da593f54-b617-4444-b10e-c5bcaed16b23.png)

**Comment by Coolie1101** [comment]
Any idea why I keep getting the following error?

```
Timeout error fetching information from http://ccab4aaf-frigate-fa-beta:5000/api/stats:
```

**Comment by blakeblackshear** [comment]
The integration looks like it's set up to point to the full access beta addon. If you have switched the the stable version of the addon, you need to remove and reconfigure the integration to update the url.

For inference speeds, lower is better. Those speeds look like USB2 speeds. Is it plugged into a USB3 port?

**Comment by Coolie1101** [comment]
I am still using the bata version.
`Frigate NVR (Full Access) Beta (0.11.0`

`Hostname
ccab4aaf-frigate-fa-beta`

**Comment by Coolie1101** [comment]
> The integration looks like it's set up to point to the full access beta addon.

Errors still persist, and I am still using the Full Access Beta version.

Also, I stopped receiving video with the automation below, I only receive the photo, any ideas?

**Automation Action**
```
action:
  - service: notify.group
    data:
      message: >-
        A {{trigger.payload_json["after"]["label"]}} was detected on the
        {{trigger.payload_json["after"]["camera"]}} camera.
      data:
        photo:
          - url: >-
              http://hass_url/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg
            caption: >-
              'A {{trigger.payload_json["after"]["label"]}} was detected at the
              Front {{trigger.payload_json["after"]["entered_zones"]}}'.
  - delay:
      seconds: 30
  - service: notify.group
    data:
      message: Video of {{trigger.payload_json["after"]["label"]}}" detected.
      data:
        video:
          - url: >-
              http://hass_url/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/{{trigger.payload_json["after"]["camera"]}}/clip.mp4
            timeout: 1000
            caption: >-
              'Video of {{trigger.payload_json["after"]["label"]}}" detected at
              the Front {{trigger.payload_json["after"]["entered_zones"]}}'.
```

**LOGS**
```
Logger: homeassistant.components.telegram_bot
Source: components/telegram_bot/__init__.py:798
Integration: Telegram bot (documentation, issues)
First occurred: March 12, 2022, 9:12:22 AM (85 occurrences)
Last logged: 8:55:11 AM

Can't send file with kwargs: {'message': 'Video of person" detected.', 'url': 'http://usidsr.easterndns.com:8123/api/frigate/notifications/1647468709.715787-tsefen/porch/clip.mp4', 'timeout': 1000, 'caption': '\'Video of person" detected at the Front [\'Porch\']\'.'}
Can't send file with kwargs: {'message': 'Video of person" detected.', 'url': 'http://usidsr.easterndns.com:8123/api/frigate/notifications/1647473117.722614-dmizdl/porch/clip.mp4', 'timeout': 1000, 'caption': '\'Video of person" detected at the Front [\'Porch\']\'.'}
Can't send file with kwargs: {'message': 'Video of person" detected.', 'url': 'http://usidsr.easterndns.com:8123/api/frigate/notifications/1647516870.548805-2cmi1j/porch/clip.mp4', 'timeout': 1000, 'caption': '\'Video of person" detected at the Front [\'Porch\']\'.'}
Can't send file with kwargs: {'message': 'Video of person" detected.', 'url': 'http://usidsr.easterndns.com:8123/api/frigate/notifications/1647518692.463201-3wb45u/porch/clip.mp4', 'timeout': 1000, 'caption': '\'Video of person" detected at the Front [\'Door\']\'.'}
Can't send file with kwargs: {'message': 'Video of person" detected.', 'url': 'http://usidsr.easterndns.com:8123/api/frigate/notifications/1647521677.710851-p4nfxt/porch/clip.mp4', 'timeout': 1000, 'caption': '\'Video of person" detected at the Front [\'Porch\']\'.'}
```

**Comment by Coolie1101** [comment]
> Nothing changed there. Check your HA logs to see if the integration needs to be reconfigured.

So, I did a fresh install and still don't see the sensors. any idea what the issue may be?

**MQTT Raw / formatted JSON**
```
{
  "porch_01": {
    "camera_fps": 5.1,
    "process_fps": 5.1,
    "skipped_fps": 0,
    "detection_fps": 0,
    "pid": 222,
    "capture_pid": 226
  },
  "south_side": {
    "camera_fps": 5,
    "process_fps": 5,
    "skipped_fps": 0,
    "detection_fps": 0,
    "pid": 224,
    "capture_pid": 227
  },
  "detectors": {
    "coral": {
      "inference_speed": 19.86,
      "detection_start": 0,
      "pid": 217
    }
  },
  "detection_fps": 0,
  "service": {
    "uptime": 263021,
    "version": "0.11.0-cbf26e0",
    "storage": {
      "/media/frigate/recordings": {
        "total": 235535.3,
        "used": 42590.8,
        "free": 183344.1,
        "mount_type": "ext4"
      },
      "/media/frigate/clips": {
        "total": 235535.3,
        "used": 42590.8,
        "free": 183344.1,
        "mount_type": "ext4"
      },
      "/tmp/cache": {
        "total": 4095,
        "used": 72.3,
        "free": 4022.7,
        "mount_type": "tmpfs"
      },
      "/dev/shm": {
        "total": 4095,
        "used": 1.3,
        "free": 4093.7,
        "mount_type": "tmpfs"
      }
    },
    "temperatures": {}
  }
}
```

**Comment by Coolie1101** [comment]
> Specifically which sensors are not working?

Pretty much all the system (nvr) sensors as mentioned above and listed below, except for the following 2.
![image](https://user-images.githubusercontent.com/28989417/164025946-1c67bc21-9cb1-4074-90c1-96049ebd07b2.png)

```
sensor.frigate_nvr_cpu_percent
sensor.frigate_nvr_memory_percent
binary_sensor.frigate_nvr_running
sensor.frigate_nvr_version
sensor.frigate_nvr_newest_version
binary_sensor.frigate_nvr_update_available
```

**Comment by blakeblackshear** [comment]
I don't think the frigate integration provides those sensors. Are those created by the supervisor for addons?

**Comment by Coolie1101** [comment]
> I don't think the frigate integration provides those sensors. Are those created by the supervisor for addons?

I'm not sure, I assume they were created by the integration, but they all disappeared after upgrading.

**Comment by blakeblackshear** [comment]
I would look in the supervisor logs. The integration doesn't create them.

**Comment by Coolie1101** [comment]
Not much pertaining to Frigate in the Supervisor Logs, except for a few entries about Frigate having full access.

**Comment by blakeblackshear** [comment]
All I know is that the integration doesn't create those sensors. I have never seen sensors like that because I do not run HassOS.

**Comment by Coolie1101** [comment]
> All I know is that the integration doesn't create those sensors.

They are indeed created by HA Supervisor, and was all disabled, not sure why, but they are all back up and running after manually re-enabling them.

![image](https://user-images.githubusercontent.com/28989417/164315035-ae68ea82-a46a-46b3-a85e-f28b1144207b.png)

**Comment by Coolie1101** [comment]
So, I still can't figure out why the below send video action in my automation don't work, I tried reaching the url from the error log directly, but got the message below, could it be an issue with the ID?

**Automation Action That Works**
```
  - service: notify.group
    data_template:
      message: Some Message.
      data:
        photo:
          - url: >-
              http://192.168.200.211:8123/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg
            caption: >-
              'A {{trigger.payload_json["after"]["label"]}} was detected at the
              Front {{trigger.payload_json["after"]["entered_zones"]}}'.
```

**Automation Action that Don't Work**
```
  - delay:
      seconds: 45
  - service: notify.group
    data_template:
      message: Video of {{trigger.payload_json["after"]["label"]}}" detected.
      data:
        video:
          - url: >-
              http://192.168.200.211:8123/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/{{trigger.payload_json["after"]["camera"]}}/clip.mp4
            timeout: 5000
            caption: >-
              'Video of {{trigger.payload_json["after"]["label"]}}" detected at
              the Front {{trigger.payload_json["after"]["entered_zones"]}}'.
```

**Error Log**
```
Logger: homeassistant.components.telegram_bot
Source: components/telegram_bot/__init__.py:809
Integration: Telegram bot ([documentation](https://www.home-assistant.io/integrations/telegram_bot), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+telegram_bot%22))
First occurred: April 27, 2022, 8:09:39 PM (22 occurrences)
Last logged: 5:47:44 PM

Can't send file with kwargs: {'message': 'Video of person" detected.', 'url': 'http://192.168.200.211:8123/api/frigate/notifications/1651261173.422286-hnxrtc/porch_01/clip.mp4', 'timeout': 5000, 'caption': '\'Video of person" detected at the Front []\'.'}
Can't send file with kwargs: {'message': 'Video of person" detected.', 'url': 'http://192.168.200.211:8123/api/frigate/notifications/1651261366.842301-994nok/porch_01/clip.mp4', 'timeout': 5000, 'caption': '\'Video of person" detected at the Front [\'Porch\']\'.'}
Can't send file with kwargs: {'message': 'Video of person" detected.', 'url': 'http://192.168.200.211:8123/api/frigate/notifications/1651262777.82933-75r8o4/porch_01/clip.mp4', 'timeout': 5000, 'caption': '\'Video of person" detected at the Front [\'Steps\', \'Porch\']\'.'}
Can't send file with kwargs: {'message': 'Video of person" detected.', 'url': 'http://192.168.200.211:8123/api/frigate/notifications/1651267569.036967-z1wjxi/porch_01/clip.mp4', 'timeout': 5000, 'caption': '\'Video of person" detected at the Front [\'Steps\', \'Porch\']\'.'}
Can't send file with kwargs: {'message': 'Some Message.', 'url': 'http://192.168.200.211:8123/api/frigate/notifications/1651268803.686459-pcti8t/south_side/clip.mp4', 'timeout': 5000, 'caption': '\'Video of person" detected on the South Side Camera.\''}
```

**Message after try to access the video directly**
URL:- `http://192.168.200.211:8123/api/frigate/notifications/1651261173.422286-hnxrtc/porch_01/clip.mp4`
Meg: `Could not create clip from recordings for porch_01.`

**Files In Folder*
![image](https://user-images.githubusercontent.com/28989417/166076597-1c43d7c9-6d99-47be-8334-16cf13f0a13a.png)
